#!/bin/bash
set -e

INSTALL_PATH=bin
BUILD_PATH=poietic-godot/.build/debug

git submodule update --init --recursive

pushd $(pwd) > /dev/null
cd poietic-godot
swift build
popd

echo Copying to ${INSTALL_PATH}
cp ${BUILD_PATH}/*.dylib  ${INSTALL_PATH}

